#!/bin/bash
openocd -f ./SQRL.program_scripts/openocd.cfg &
sleep 1
(echo "init"; echo "jtagspi_init 0 ./SQRL.program_scripts/bscan_spi_xc7a200t.bit"; echo "jtagspi_program ./SQRL.runs/impl_1/SQRL_top.bin 0x0"; echo "fpga_program"; echo "exit"; echo "quit"; sleep 30) | telnet localhost 4444
pkill -f openocd
